In [2]:
import pandas as pd

In [8]:
df = pd.read_csv('Students_exams.csv')
df.head()

   gender  math score  reading score  writing score
0  female          72             72             74
1  female          69             90             88
2  female          90             95             93
3    male          47             57             44
4    male          76             78             75

In [9]:
gender = df["gender"]
gender

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: object

In [11]:
math = df["math score"]
math

0      72
1      69
2      90
3      47
4      76
       ..
995    88
996    62
997    59
998    68
999    77
Name: math score, Length: 1000, dtype: int64

In [12]:
students = df[["gender" , "math score"]]
students

     gender  math score
0    female          72
1    female          69
2    female          90
3      male          47
4      male          76
..      ...         ...
995  female          88
996    male          62
997  female          59
998  female          68
999  female          77

[1000 rows x 2 columns]

In [14]:
rows = df[2:7]
rows

   gender  math score  reading score  writing score
2  female          90             95             93
3    male          47             57             44
4    male          76             78             75
5  female          71             83             78
6  female          88             95             92

In [16]:
result = df.loc[0]
result

gender           female
math score           72
reading score        72
writing score        74
Name: 0, dtype: object

In [18]:
result = df.loc[[1,3,999]]
result

     gender  math score  reading score  writing score
1    female          69             90             88
3      male          47             57             44
999  female          77             86             86

In [19]:
result = df.loc[[1,3,999] ,['gender']]
result

     gender
1    female
3      male
999  female

In [20]:
result = df.loc[: ,['gender']]
result

     gender
0    female
1    female
2    female
3      male
4      male
..      ...
995  female
996    male
997  female
998  female
999  female

[1000 rows x 1 columns]

In [21]:
result = df.loc[15:30 ,['gender']]
result

    gender
15  female
16    male
17  female
18    male
19  female
20    male
21  female
22    male
23  female
24    male
25    male
26    male
27  female
28    male
29  female
30  female

In [22]:
result = df.iloc[0]
result

gender           female
math score           72
reading score        72
writing score        74
Name: 0, dtype: object

In [23]:
result = df.iloc[[1,999],[0,3]]
result

     gender  writing score
1    female             88
999  female             86