In [1]:
import pandas as pd

In [2]:
df1 =pd.DataFrame({'city' : ['A' , 'B','C' ] ,
                  'day1' : [22 ,5,28] ,
                  'day2' : [10 ,14,13] ,
                  'day3' : [22 ,15,26] ,
                  'day4' : [18 ,15,17] ,
                  'day5' : [12 ,14,28] ,
                  })

In [3]:
df1.melt(id_vars=['city'])

   city variable  value
0     A     day1     22
1     B     day1      5
2     C     day1     28
3     A     day2     10
4     B     day2     14
5     C     day2     13
6     A     day3     22
7     B     day3     15
8     C     day3     26
9     A     day4     18
10    B     day4     15
11    C     day4     17
12    A     day5     12
13    B     day5     14
14    C     day5     28

In [6]:
df1.melt(id_vars=['city'] , var_name = 'date', value_name = 'temperature')

   city  date  temperature
0     A  day1           22
1     B  day1            5
2     C  day1           28
3     A  day2           10
4     B  day2           14
5     C  day2           13
6     A  day3           22
7     B  day3           15
8     C  day3           26
9     A  day4           18
10    B  day4           15
11    C  day4           17
12    A  day5           12
13    B  day5           14
14    C  day5           28

In [7]:
df1.melt(id_vars=['city'] , var_name = 'date', value_name = 'temperature').sort_values(by = 'city')

   city  date  temperature
0     A  day1           22
3     A  day2           10
6     A  day3           22
9     A  day4           18
12    A  day5           12
1     B  day1            5
4     B  day2           14
7     B  day3           15
10    B  day4           15
13    B  day5           14
2     C  day1           28
5     C  day2           13
8     C  day3           26
11    C  day4           17
14    C  day5           28

In [8]:
df1.melt(id_vars=['city'] , var_name = 'date', value_name = 'temperature').sort_values(by = 'city').reset_index(drop = True)

   city  date  temperature
0     A  day1           22
1     A  day2           10
2     A  day3           22
3     A  day4           18
4     A  day5           12
5     B  day1            5
6     B  day2           14
7     B  day3           15
8     B  day4           15
9     B  day5           14
10    C  day1           28
11    C  day2           13
12    C  day3           26
13    C  day4           17
14    C  day5           28