In [2]:
import pandas as pd

df =pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

In [3]:
df =pd.read_csv('Students_exams.csv')
print(df)

     gender  math score  reading score  writing score
0    female          72             72             74
1    female          69             90             88
2    female          90             95             93
3      male          47             57             44
4      male          76             78             75
..      ...         ...            ...            ...
995  female          88             99             95
996    male          62             55             55
997  female          59             71             65
998  female          68             78             77
999  female          77             86             86

[1000 rows x 4 columns]

In [4]:
df =pd.read_csv('Students.csv')
print(df)

    gender;math score;reading score;writing score
0                                 female;72;72;74
1                                 female;69;90;88
2                                 female;90;95;93
3                                   male;47;57;44
4                                   male;76;78;75
..                                            ...
995                               female;88;99;95
996                                 male;62;55;55
997                               female;59;71;65
998                               female;68;78;77
999                               female;77;86;86

[1000 rows x 1 columns]

In [5]:
df =pd.read_csv('Students.csv' , sep =';')
print(df)

     gender  math score  reading score  writing score
0    female          72             72             74
1    female          69             90             88
2    female          90             95             93
3      male          47             57             44
4      male          76             78             75
..      ...         ...            ...            ...
995  female          88             99             95
996    male          62             55             55
997  female          59             71             65
998  female          68             78             77
999  female          77             86             86

[1000 rows x 4 columns]

In [6]:
df.shape

(1000, 4)

In [7]:
df =pd.read_csv('Students_exams.csv' , usecols=['gender' ,'reading score'])
print(df)

     gender  reading score
0    female             72
1    female             90
2    female             95
3      male             57
4      male             78
..      ...            ...
995  female             99
996    male             55
997  female             71
998  female             78
999  female             86

[1000 rows x 2 columns]

In [8]:
df =pd.read_csv('Students_exams.csv' , usecols=['gender' ,'reading score'] , nrows= 200)
print(df)

     gender  reading score
0    female             72
1    female             90
2    female             95
3      male             57
4      male             78
..      ...            ...
195    male             55
196    male             69
197    male             56
198  female             53
199  female             79

[200 rows x 2 columns]

In [9]:
df.head()

   gender  reading score
0  female             72
1  female             90
2  female             95
3    male             57
4    male             78

In [10]:
df.head(10)

   gender  reading score
0  female             72
1  female             90
2  female             95
3    male             57
4    male             78
5  female             83
6  female             95
7    male             43
8    male             64
9  female             60

In [11]:
df.tail()

     gender  reading score
195    male             55
196    male             69
197    male             56
198  female             53
199  female             79

In [12]:
df.tail(20)

     gender  reading score
180    male             68
181  female             64
182  female             50
183  female             69
184    male             52
185    male             67
186    male             76
187    male             66
188    male             52
189  female             88
190  female             65
191    male             83
192  female             64
193    male             62
194  female             84
195    male             55
196    male             69
197    male             56
198  female             53
199  female             79

In [13]:
df = pd.read_csv("Students_no_cols.csv")
df

     female  72  72.1  74
0    female  69    90  88
1    female  90    95  93
2      male  47    57  44
3      male  76    78  75
4    female  71    83  78
..      ...  ..   ...  ..
994  female  88    99  95
995    male  62    55  55
996  female  59    71  65
997  female  68    78  77
998  female  77    86  86

[999 rows x 4 columns]

In [14]:
header_names=['A','B','C','D']
df = pd.read_csv("Students_no_cols.csv", names=header_names)
df

          A   B   C   D
0    female  72  72  74
1    female  69  90  88
2    female  90  95  93
3      male  47  57  44
4      male  76  78  75
..      ...  ..  ..  ..
995  female  88  99  95
996    male  62  55  55
997  female  59  71  65
998  female  68  78  77
999  female  77  86  86

[1000 rows x 4 columns]